### ISSUE TITLE
Home assitant si blocca dopo distacco carico

### ISSUE THREAD

**Issue by alexcoscia** [andbad/HA_PowerControl#45]
**Informazioni sul sistema**
 _- Versione Home Assistant_core 2024.5.5 supervisor 2024.5.01
 _- Tipo installazione HAOS 12.3 su Raspberry 4
 _- Versione package 3.5(ultima)
 _- HAI ATTIVATO I LOG? Si

**Descrivi il problema**
Dopo svariati e svariati test sulle possibili cause di blocchi apparentemente senza senso di HA, ho notato che dopo aver distaccato un qualsiasi carico , il sistema si blocca e non riesco ad accedere ad HA, dopo un po' di tempo ritorna tutto normale. Ho notato infatti dal grafico, che non legge neanche più i valori di assorbimento impianto.**E ATTIVA I LOG**!_

**Passi per riprodurre il problema**
Indicazioni su come riprodurre le condizioni che hanno portato al bug:
_1. Vai qui '...'_
_2. Clicca la '....'_
_3. Scrolla giù '....'_
_4. Riavvia di su '...'_
_etc...__
_**PERÒ ATTIVA I LOG!**_

**Cosa ti aspettavi**
Descrizione breve del comportamento che ti aspettavi
**DOPO AVER ATTIVATO I LOG!**

**Screenshots**
_Se applicabile alla tua problematica, posta uno [screeshot._]
![Screenshot_2024-06-03-14-01-25-667_io homeassistant companion android](https://github.com/andbad/HA_PowerControl/assets/101573852/2790f478-d261-487c-bb8e-939990b4d3cc)

**E SE ANCORA NON L'HAI FATTO, ATTIVA I LOG!**

**Log:**
2024-06-03 12:26:04.976 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.978 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.980 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.982 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.986 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.989 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.991 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration var which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.993 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.995 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:04.998 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pun_sensor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:05.000 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hass_agent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:05.002 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:05.004 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:05.006 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:05.008 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:05.010 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:05.012 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-03 12:26:06.961 WARNING (MainThread) [homeassistant.config] Package centro_controllo_forno_1_3 contains invalid customize
2024-06-03 12:26:06.961 WARNING (MainThread) [homeassistant.config] Package centro_controllo_lavastoviglie_1_2 contains invalid customize
2024-06-03 12:26:06.962 WARNING (MainThread) [homeassistant.config] Package centro_controllo_lavatrice_2_0 contains invalid customize
2024-06-03 12:26:06.963 WARNING (MainThread) [homeassistant.config] Package sensor_template_package contains invalid customize
2024-06-03 12:26:08.288 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=597 from 2024-06-03 09:30:38)
2024-06-03 12:26:08.615 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /addons/cebe7a76_hassio_google_drive_backup/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/cebe7a76_hassio_google_drive_backup/changelog')
2024-06-03 12:26:08.615 WARNING (MainThread) [homeassistant.components.hassio.data] Could not fetch changelog for cebe7a76_hassio_google_drive_backup: 
2024-06-03 12:26:11.286 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering '{{ as_timestamp(states.input_boolean.durata_cotture.last_changed) }}'
2024-06-03 12:26:11.287 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering '{{ as_timestamp(states.input_boolean.durata_cotture.last_changed) }}'
2024-06-03 12:26:11.392 ERROR (MainThread) [homeassistant.components.history_stats.helpers] Error parsing template for field start
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2044, in forgiving_as_timestamp
    return dt_util.as_timestamp(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in as_timestamp
    raise ValueError("not a valid date/time.")
ValueError: not a valid date/time.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 585, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2600, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2047, in forgiving_as_timestamp
    raise_no_default("as_timestamp", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1849, in raise_no_default
    raise ValueError(
ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_cotture.last_changed) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/history_stats/helpers.py", line 40, in async_calculate_period
    rendered = template.async_render()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 587, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_cotture.last_changed) }}' but no default was specified
2024-06-03 12:26:11.427 ERROR (MainThread) [homeassistant.components.history_stats.coordinator] Error fetching Durata Cotture data: ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_cotture.last_changed) }}' but no default was specified
2024-06-03 12:26:11.428 WARNING (MainThread) [homeassistant.components.sensor] Platform history_stats not ready yet: ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_cotture.last_changed) }}' but no default was specified; Retrying in background in 30 seconds
2024-06-03 12:26:11.449 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering '{{ as_timestamp(states.input_boolean.durata_lavaggio_stoviglie.last_changed) }}'
2024-06-03 12:26:11.450 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering '{{ as_timestamp(states.input_boolean.durata_lavaggio_stoviglie.last_changed) }}'
2024-06-03 12:26:11.450 ERROR (MainThread) [homeassistant.components.history_stats.helpers] Error parsing template for field start
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2044, in forgiving_as_timestamp
    return dt_util.as_timestamp(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in as_timestamp
    raise ValueError("not a valid date/time.")
ValueError: not a valid date/time.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 585, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2600, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2047, in forgiving_as_timestamp
    raise_no_default("as_timestamp", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1849, in raise_no_default
    raise ValueError(
ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_lavaggio_stoviglie.last_changed) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/history_stats/helpers.py", line 40, in async_calculate_period
    rendered = template.async_render()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 587, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_lavaggio_stoviglie.last_changed) }}' but no default was specified
2024-06-03 12:26:11.466 ERROR (MainThread) [homeassistant.components.history_stats.coordinator] Error fetching Durata Lavaggio Stoviglie data: ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_lavaggio_stoviglie.last_changed) }}' but no default was specified
2024-06-03 12:26:11.467 WARNING (MainThread) [homeassistant.components.sensor] Platform history_stats not ready yet: ValueError: Template error: as_timestamp got invalid input '' when rendering template '{{ as_timestamp(states.input_boolean.durata_lavaggio_stoviglie.last_changed) }}' but no default was specified; Retrying in background in 30 seconds
2024-06-03 12:26:11.778 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.last_update_centro_controllo_lavastoviglie }}'
2024-06-03 12:26:11.781 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.last_update_centro_controllo_energia }}'
2024-06-03 12:26:11.797 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.last_update_centro_controllo_lavatrice }}'
2024-06-03 12:26:11.808 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.last_update_centro_controllo_forno }}'
2024-06-03 12:26:14.029 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.036 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.045 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.052 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_DRY was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.060 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_FAN_ONLY was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.066 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_AUTO was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.073 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.082 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:14.089 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_SWING_MODE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:15.021 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE: 9>, please report it to the author of the 'smartir' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-06-03 12:26:15.021 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:15.022 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:15.022 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) implements HVACMode(s): off, cool, dry, heat, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:15.041 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smartir' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/smartir/climate.py, line 175: async_track_state_change(self.hass, self._temperature_sensor,, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:15.048 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smartir' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/smartir/climate.py, line 183: async_track_state_change(self.hass, self._humidity_sensor,, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:15.055 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'smartir' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/smartir/climate.py, line 191: async_track_state_change(self.hass, self._power_sensor,, please report it to the author of the 'smartir' custom integration
2024-06-03 12:26:15.069 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should

**Informazioni aggiuntive**
_Altre informazioni che potrebbero sembrarti utili._

**Comment by andbad** [comment]
Nei log che hai mandato non vi sono righe relative al package, sicuro di
[averli abilitati](https://github.com/andbad/HA_PowerControl#debug)?

Sarebbe utile anche avere uno screeshot della configurazione del package,
comunque dal grafico vedo che il recorder ha smesso di registrare valori
almeno 5 minuti dopo che il package ha disattivato e poi riattivato un
carico. Dai log forse si capirebbe di più.

By(t)e





Il giorno lun 3 giu 2024 alle ore 14:24 alexcoscia ***@***.***>
ha scritto:

**Comment by alexcoscia** [comment]
[home-assistant.log](https://github.com/user-attachments/files/15555015/home-assistant.log)
ho allegato il log. 
sembra che gli script vadano in loop impallando il sistema.

**Comment by alexcoscia** [comment]
Allego anche le foto della mia configurazione 
![Screenshot_2024-06-04-15-05-53-918_io homeassistant companion android](https://github.com/andbad/HA_PowerControl/assets/101573852/a390ee3a-4256-4e4b-843f-8001d5ef5a52)
![Screenshot_2024-06-04-15-05-47-853_io homeassistant companion android](https://github.com/andbad/HA_PowerControl/assets/101573852/f9275ba8-4a76-4a3e-824b-061f97be25ee)

**Comment by alexcoscia** [comment]
Problema risolto. Il tutto era dovuto alla mancanza di configurazione di notify.tutti. non lo avevo configurato per scelta, perché non mi interessavano le notifiche, ma evidentemente non si può. Grazie mille per il lavoro svolto allo/agli sviluppatori

**Comment by andbad** [comment]
Grazie, stavo guardando ora i log e avevo notato l'errore.
Provo a capire se sia possibile evitarlo.
Ho anche notato che hai configurato un tempo di attesa tra un distacco ed il seguente di 1 secondo, a mio avviso è un po' troppo basso. Se noti comportamenti anomali prova ad aumentarlo almeno a 5-10 secondi (considera che il tempo di intervento del contatore è tra 1 o 2 minuti, quindi anche con 15 secondi tra un distacco e l'altro riusciresti a distaccare 4 carichi minimo).

By(t)e

**Comment by andbad** [comment]
Dovrei aver risolto il problema: così lo script non si blocca anche in caso di assenza del gruppo di notifica.
https://github.com/andbad/HA_PowerControl/releases/tag/v3.51

By(t)e

**Comment by alexcoscia** [comment]
Grazie mille, provo stasera e ti do un riscontro senza notifiche. Per ora
ho provato con le notifiche e va bene anche con tempo di un secondo. Grazie
mille

Il mer 5 giu 2024, 11:36 andbad ***@***.***> ha scritto:

**Comment by alexcoscia** [comment]
Versione controllo carichi ultima (3.51c)
Supervisore 2024.06.2
Core 2024.6.4
Os 12.4
Raspberry pi4
[home-assistant ok.log](https://github.com/user-attachments/files/16011496/home-assistant.ok.log)
![Screenshot_2024-06-27-11-47-11-173_io homeassistant companion android](https://github.com/andbad/HA_PowerControl/assets/101573852/f3faf9b9-518c-4318-80be-3a638b0221d8)
![Screenshot_2024-06-27-11-46-19-306_io homeassistant companion android]
(https://github.com/andbad/HA_PowerControl/assets/101573852/62b77c7f-7f14-4b79-b8a5-f0fefcb4f92a)
Solito problema che capita anche con notifiche attivate.  Non ne vengo a capo

**Comment by alexcoscia** [comment]
Questo è il file PC.yaml funzionante. Ho fatto una settimana di test e non è più andato in loop e di conseguenza non si blocca e riavvia HA

**Comment by andbad** [comment]
La tua soluzione non mi convince. L'automazione dev'essere eseguita fintanto che la potenza sospesa è maggiore di zero (ovvero quando dei carichi erano sospesi e non sono stati riattivati), quando è zero deve fermarsi (perché non ci sono più carichi da riattivare).
Se imposti come condizione ">=0", lo script continua a girare per sempre, che ovviamente non è quello che vogliamo.

Analizzando i tuoi log, ho notato un'anomalia:
```
2024-06-27 10:29:37.543 DEBUG (MainThread) [homeassistant.components.pc] Avvio script start carico 10
2024-06-27 10:29:37.548 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Avvio
2024-06-27 10:29:37.550 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Condition 1 ok
2024-06-27 10:29:37.551 DEBUG (MainThread) [homeassistant.components.pc] Script Stop Carico vetrina_bar_pw - Condition 1.5 - Ok
2024-06-27 10:29:37.555 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Condition 2 ok
2024-06-27 10:29:37.557 DEBUG (MainThread) [homeassistant.components.pc] Script Stop Carico vetrina_bar_pw - Condition 2.5 - Ok
2024-06-27 10:29:37.558 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Condition 3 ok
2024-06-27 10:29:37.562 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Condition 4 ok
2024-06-27 10:29:37.564 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Condition 5 ok
2024-06-27 10:29:37.570 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Resettata potenza sospesa
2024-06-27 10:29:37.577 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Attivato interruttore
**2024-06-27 10:29:37.584 DEBUG (MainThread) [homeassistant.components.pc] Avvio script start carichi: sospesa (0) > 0**
2024-06-27 10:29:37.906 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico vetrina_bar_pw - Inviata notifica. Attendo 1.0 minuti
2024-06-27 10:30:37.912 DEBUG (MainThread) [homeassistant.components.pc] Avvio script start carico 11
2024-06-27 10:30:37.922 DEBUG (MainThread) [homeassistant.components.pc] Script Start Carico None - Avvio
```

Nella riga evidenziata si vede che viene riavviato lo script start_carichi_generale, cosa che non dovrebbe accadere perché è già in esecuzione (infatti poi prosegue con lo script già in corso).
Non riesco a spiegarmelo.

By(t)e

**Comment by andbad** [comment]
Forse ho capito. Prova questa versione, se hai tempo:
https://github.com/andbad/HA_PowerControl/tree/45-home-assitant-si-blocca-dopo-distacco-carico

By(t)e

**Comment by alexcoscia** [comment]
In realtà se imposti solo > 0 il risultato da true solo se è maggiore, se è
= 0 da false e di conseguenza va in loop

Il gio 4 lug 2024, 13:11 andbad ***@***.***> ha scritto:

**Comment by alexcoscia** [comment]
Ho fatto le prove col file aggiornato e purtroppo il problema non è risolto. allego i due LOG (2) con la versione testata oggi, la (3) con la versione modificata da me. da quel che posso capire io (poco), dai log se come dici giustamente te andasse in loop, si dovrebbe vedere. Invece addirittura non ho trovato il punto dove dal valore di potenza sospesa (0) > 0 .
Poi googlando ho trovato [questo](https://community.home-assistant.io/t/script-repeat-until-continues-after-condition-met/317622/3), non so se possa essere il problema.
[home-assistant (2).log](https://github.com/user-attachments/files/16102027/home-assistant.2.log)
[home-assistant (3).log](https://github.com/user-attachments/files/16102028/home-assistant.3.log)

**Comment by andbad** [comment]
> Ho fatto le prove col file aggiornato e purtroppo il problema non è risolto. allego i due LOG (2) con la versione testata oggi, la (3) con la versione modificata da me. da quel che posso capire io (poco), dai log se come dici giustamente te andasse in loop, si dovrebbe vedere. Invece addirittura non ho trovato il punto dove dal valore di potenza sospesa (0) > 0 . Poi googlando ho trovato [questo](https://community.home-assistant.io/t/script-repeat-until-continues-after-condition-met/317622/3), non so se possa essere il problema. 
La modifica nella versione che ti ho fatto provare mirava proprio a evitare l'eventualità che viene citata in quel post, ma sarebbe la conseguenza del tuo problema di loop, piuttosto che la causa.

Sospetto che sia qualcosa legato al tipo di dato, perché dai tuoi log leggo:
`2024-07-04 19:35:13.596 DEBUG (MainThread) [homeassistant.components.pc] Script Stop Carico Forno beko - Spostata potenza da carico 1892.844 a sospesa 1892 (dovrebbero essere uguali).`

e come vedi i due valori non sono uguali: il primo è un float, il secondo un int.
Ho fatto un po' di modifiche, se hai voglia e tempo puoi provare questa versione aggiornata.
https://github.com/andbad/HA_PowerControl/edit/45-home-assitant-si-blocca-dopo-distacco-carico/packages/pc.yaml

Grazie mille per l'aiuto.

By(t)e

**Comment by alexcoscia** [comment]
In realtà lo avevo pensato anche io, infatti avevo già trasformato tutti
gli altri valori in int. Quella ed un altra le leggo da due prese tapo TP
link e mi sembra che nn ci sia possibilità di modificarle se non attraverso
il configuration.yaml . Però rimango dubbioso del fatto che con la mia
modifica tutto funziona perfettamente e non si blocca mai...cmq se ho un
po' di tempo provo la nuova versione. Ci aggiorniamo e grazie a te per il
lavoro che fai ed hai fatto...

Il ven 5 lug 2024, 10:38 andbad ***@***.***> ha scritto:
